// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/projects" | "/projects/[projectId]" | "/projects/[projectId]/artifacts" | "/projects/[projectId]/backlog" | "/projects/[projectId]/canvas" | "/projects/[projectId]/overview" | "/projects/[projectId]/review"
type AppRouteHandlerRoutes = "/api/artifacts/[artifactId]/sections/[sectionId]" | "/api/artifacts/[artifactId]/sections/[sectionId]/regenerate" | "/api/health" | "/api/projects" | "/api/projects/[projectId]" | "/api/projects/[projectId]/artifacts" | "/api/projects/[projectId]/clarification" | "/api/projects/[projectId]/edges" | "/api/projects/[projectId]/nodes" | "/api/projects/[projectId]/nodes/[nodeId]" | "/api/projects/[projectId]/nodes/[nodeId]/expand" | "/api/projects/[projectId]/sync-model"
type PageRoutes = never
type LayoutRoutes = "/" | "/projects/[projectId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/artifacts/[artifactId]/sections/[sectionId]": { "artifactId": string; "sectionId": string; }
  "/api/artifacts/[artifactId]/sections/[sectionId]/regenerate": { "artifactId": string; "sectionId": string; }
  "/api/health": {}
  "/api/projects": {}
  "/api/projects/[projectId]": { "projectId": string; }
  "/api/projects/[projectId]/artifacts": { "projectId": string; }
  "/api/projects/[projectId]/clarification": { "projectId": string; }
  "/api/projects/[projectId]/edges": { "projectId": string; }
  "/api/projects/[projectId]/nodes": { "projectId": string; }
  "/api/projects/[projectId]/nodes/[nodeId]": { "projectId": string; "nodeId": string; }
  "/api/projects/[projectId]/nodes/[nodeId]/expand": { "projectId": string; "nodeId": string; }
  "/api/projects/[projectId]/sync-model": { "projectId": string; }
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/projects/[projectId]/artifacts": { "projectId": string; }
  "/projects/[projectId]/backlog": { "projectId": string; }
  "/projects/[projectId]/canvas": { "projectId": string; }
  "/projects/[projectId]/overview": { "projectId": string; }
  "/projects/[projectId]/review": { "projectId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/projects/[projectId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
